In [2]:
import pandas as pd
import numpy as np
import statistics 
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_validate, StratifiedKFold
from sklearn.svm import SVC

In [3]:
X = pd.read_csv("data/X.csv", sep=' ', header=None, dtype=float)
X = X.values

In [4]:
y = pd.read_csv("data/y_bush_vs_others.csv", header=None)
y_bush = y.values.ravel()
y = pd.read_csv("data/y_williams_vs_others.csv", header=None)
y_williams = y.values.ravel()

In [5]:
X.shape

(13233, 4096)

In [6]:
np.sum(y_bush)

530

In [7]:
y_williams.shape

(13233,)

In [125]:
pca = PCA(n_components=2000)
X_pca = pca.fit_transform(X)
print(X_pca.shape)
X_pca

(13233, 2000)


array([[-6.17302394e+00, -1.83102506e+00, -6.82618249e-01, ...,
         6.98684853e-03, -7.50509013e-02, -4.43466925e-02],
       [-8.74472615e+00, -1.06152081e+00,  4.39499342e+00, ...,
         4.74792249e-02,  3.50619466e-02, -3.73746923e-02],
       [-5.58314778e+00,  3.12191247e+00, -1.73468030e+00, ...,
         1.03409143e-01, -2.58186683e-02,  4.58111268e-03],
       ...,
       [-1.15627879e+01, -3.03118032e+00, -1.31590288e+00, ...,
        -1.77078312e-02,  3.16146911e-02,  1.47936544e-02],
       [-1.29620813e+01, -3.61012008e+00,  2.00276782e+00, ...,
        -3.85147482e-03, -2.49218550e-02, -3.07390425e-02],
       [-3.23516636e+00, -4.68425394e+00, -1.80796164e+00, ...,
         9.87610985e-03, -4.47723228e-03, -3.84094743e-03]])

In [134]:
svc3 = SVC(C = 1000, kernel = 'linear')

In [135]:
startified_cv_results = cross_validate(svc3, X_pca, y_williams, cv=StratifiedKFold(n_splits = 3, shuffle=True, random_state=7392), scoring=('precision', 'recall', 'f1'), return_train_score=False)

In [136]:
startified_cv_results

{'fit_time': array([4.738132  , 5.73593879, 6.74808598]),
 'score_time': array([5.20861411, 7.12185597, 6.85193777]),
 'test_precision': array([0.63636364, 0.875     , 0.77777778]),
 'test_recall': array([0.38888889, 0.41176471, 0.41176471]),
 'test_f1': array([0.48275862, 0.56      , 0.53846154])}

In [137]:
fit_timemean = statistics.mean(startified_cv_results['test_f1'])
print("test_f1 mean is:", fit_timemean)

test_f1 mean is: 0.5270733863837312


In [200]:
pca = PCA(n_components=1600)
X_pca = pca.fit_transform(X)
print(X_pca.shape)
X_pca

(13233, 1000)


array([[-6.17302394e+00, -1.83102506e+00, -6.82618249e-01, ...,
        -1.16323404e-01, -6.60217768e-02, -2.71023901e-01],
       [-8.74472615e+00, -1.06152081e+00,  4.39499342e+00, ...,
        -1.38566465e-01, -1.76105245e-01, -1.06188684e-02],
       [-5.58314778e+00,  3.12191247e+00, -1.73468030e+00, ...,
         5.76000445e-02,  6.65109438e-02, -6.75396672e-02],
       ...,
       [-1.15627879e+01, -3.03118032e+00, -1.31590288e+00, ...,
         7.83137361e-02,  8.42509685e-02, -6.07774916e-02],
       [-1.29620813e+01, -3.61012008e+00,  2.00276782e+00, ...,
         3.89656485e-02,  9.50583383e-03, -6.40079122e-02],
       [-3.23516636e+00, -4.68425394e+00, -1.80796164e+00, ...,
         1.70366634e-01, -3.59922953e-02, -4.60972326e-02]])

In [209]:
svc4 = SVC(C = 100, kernel = 'rbf')

In [210]:
startified_cv_results = cross_validate(svc4, X_pca, y_williams, cv=StratifiedKFold(n_splits = 3, shuffle=True, random_state=7392), scoring=('precision', 'recall', 'f1'), return_train_score=False)

In [211]:
startified_cv_results

{'fit_time': array([2.40967798, 2.58100009, 2.43026114]),
 'score_time': array([3.03738427, 3.39584494, 3.20498681]),
 'test_precision': array([0.66666667, 0.8       , 1.        ]),
 'test_recall': array([0.22222222, 0.47058824, 0.35294118]),
 'test_f1': array([0.33333333, 0.59259259, 0.52173913])}

In [212]:
fit_timemean = statistics.mean(startified_cv_results['test_f1'])
print("test_f1 mean is:", fit_timemean)

test_f1 mean is: 0.4825550187869029


In [13]:
pca = PCA(n_components=1600)
X_pca = pca.fit_transform(X)
print(X_pca.shape)
X_pca

(13233, 1600)


array([[-6.17302394e+00, -1.83102506e+00, -6.82618249e-01, ...,
         2.11741329e-02,  7.47326788e-02, -6.95640979e-02],
       [-8.74472615e+00, -1.06152081e+00,  4.39499342e+00, ...,
        -2.55249715e-02, -1.50870876e-02, -7.85137378e-02],
       [-5.58314778e+00,  3.12191247e+00, -1.73468030e+00, ...,
         6.38931488e-02,  5.89599259e-02, -1.14193049e-01],
       ...,
       [-1.15627879e+01, -3.03118032e+00, -1.31590288e+00, ...,
        -2.38688925e-02, -3.58446083e-02,  1.65023548e-02],
       [-1.29620813e+01, -3.61012008e+00,  2.00276782e+00, ...,
         2.89238170e-02,  8.40648060e-02,  3.40262789e-02],
       [-3.23516636e+00, -4.68425394e+00, -1.80796164e+00, ...,
        -3.17508708e-02,  1.12168250e-02, -2.10019892e-02]])

In [14]:
svc1 = SVC(C = 5, kernel = 'poly', degree=9, coef0=100)

In [15]:
startified_cv_results = cross_validate(svc1, X_pca, y_williams, cv=StratifiedKFold(n_splits = 3, shuffle=True, random_state=7392), scoring=('precision', 'recall', 'f1'), return_train_score=False)

In [16]:
startified_cv_results

{'fit_time': array([3.65529609, 3.81352401, 3.74575686]),
 'score_time': array([4.06904697, 4.39719129, 4.13387609]),
 'test_precision': array([0.63636364, 0.875     , 0.7       ]),
 'test_recall': array([0.38888889, 0.41176471, 0.41176471]),
 'test_f1': array([0.48275862, 0.56      , 0.51851852])}

In [17]:
fit_timemean = statistics.mean(startified_cv_results['test_f1'])
print("test_f1 mean is:", fit_timemean)

test_f1 mean is: 0.5204257130693912
